import axios from 'axios';

export const GET_AUTHORIZATION_START = 'GET_AUTHORIZATION_START'
export const GET_AUTHORIZATION_SUCCESS = 'GET_AUTHORIZATION_SUCCESS'
export const GET_AUTHORIZATION_FAILURE = 'GET_AUTHORIZATION_FAILURE'

export const 
